### ISSUE TITLE
Documentation Progress

### ISSUE THREAD

**Issue by barreeeiroo** [Kodular/Documentation#1]
-  [x] Getting Started
  	-  [x] Overview
  	-  [x] Live Development
    	-  [x] Overview
    	-  [x] Via WiFi
    	-  [x] Via USB
  	-  [x] Extensions
    	-  [x] Overview
    	-  [x] Create Extensions
  	-  [x] Other
    	-  [x] Overview
    	-  [x] Resources
      		-  [x] Overview
      		-  [x] Concept Cards
    	-  [x] Release Notes
    	-  [x] Backpack
    	-  [x] Terms of Service
-  [ ] Components
	-  [x] Overview
	-  [ ] Screen
	-  [ ] User Interface
		-  [x] Overview
		-  [x] Bottom Sheet
		-  [x] Button
		-  [x] Checkbox
		-  [x] Circular Progress
		-  [ ] Date Picker
		-  [ ] Floating Action Button
		-  [ ] Image
		-  [ ] Label
		-  [x] Linear Progressbar
		-  [ ] List Picker
		-  [ ] List View
		-  [ ] List View Image and Text
		-  [ ] Notifier
		-  [ ] Radio Button
		-  [ ] Rating Bar
		-  [ ] Slider
		-  [ ] Snackbar
		-  [ ] Spinner
		-  [ ] Spotlight
		-  [ ] Switch
		-  [ ] Tab Layout
		-  [ ] TextBox
		-  [ ] Time Picker
		-  [ ] View Flipper
		-  [ ] View Pager
		-  [ ] Web Viewer
  	-  [ ] Layout
		-  [x] Overview
		-  [ ] Horizontal Arrangement
		-  [ ] Horizontal Arrangement
		-  [ ] Horizontal Scroll Arrangement
		-  [ ] Side Menu Layout
		-  [ ] Space
		-  [ ] Surface View
		-  [ ] Swipe Refresh Layout
		-  [ ] Table Arrangement
		-  [ ] Vertical Arrangement
		-  [ ] Vertical Scroll Arrangement
  	-  [ ] Media
		-  [x] Overview
		-  [ ] Audio Picker
		-  [ ] Camcorder
		-  [ ] Camera
		-  [ ] Exoplayer
		-  [ ] Image Picker
		-  [ ] Metadata
		-  [ ] OCR
		-  [ ] Player
		-  [ ] QR Code
		-  [ ] Sound
		-  [ ] Sound Recorder
		-  [ ] Speech Recognizer
		-  [ ] Text To Speech
		-  [ ] Video Picker
		-  [ ] Video Player
		-  [ ] Yandex Translate
		-  [ ] YouTube Player
  	-  [ ] Drawing and Animation
		-  [x] Overview
		-  [ ] Animation Util
		-  [ ] Ball
		-  [ ] Canvas
		-  [ ] Image Editor
		-  [ ] Image Sprite
  	-  [ ] Maps
		-  [x] Overview
		-  [ ] Circle
		-  [ ] Feature Collection
		-  [ ] Line String
		-  [ ] Map
		-  [ ] Marker
		-  [ ] Polygon
		-  [ ] Rectangle
  	-  [ ] Sensors
		-  [x] Overview
		-  [ ] Accelerometer
		-  [ ] Barcode Scanner
		-  [ ] Clock
		-  [ ] Fingerprint
		-  [ ] Gravity Sensor
		-  [ ] Gyroscope Sensor
		-  [ ] Light Sensor
		-  [ ] Location Sensor
		-  [ ] Magnetic Field Sensor
		-  [ ] NearField
		-  [ ] Orientation Sensor
		-  [ ] Pedometer
		-  [ ] Pressure Sensor
		-  [ ] Proximity Sensor
		-  [ ] Sound Sensor
		-  [ ] Temperature Sensor
  	-  [ ] Social
		-  [x] Overview
		-  [ ] Contact Picker
		-  [ ] Email Picker
		-  [ ] Google Account Picker
		-  [ ] Phone Call
		-  [ ] Phone Number Picker
		-  [ ] Sharing
		-  [ ] Texting
		-  [ ] Twitter
  	-  [ ] Storage
		-  [x] Overview
		-  [x] Cloudinary
		-  [ ] File
		-  [ ] Firebase DB
		-  [ ] Fusiontables Control
		-  [ ] Spreadsheet
		-  [ ] SQLite
		-  [ ] Tiny DB
		-  [ ] Tiny Web DB
  	-  [ ] Device
		-  [x] Overview
		-  [x] Audio
		-  [x] Device Tools
		-  [x] Package
		-  [x] Screenshot
		-  [x] Wallpaper
  	-  [ ] Dynamic Components
		-  [x] Overview
		-  [ ] Dynamic Button
		-  [ ] Dynamic Label
		-  [ ] Dynamic Textbox
  	-  [ ] Connectivity
		-  [x] Overview
		-  [ ] Activity Starter
		-  [ ] Arduino
		-  [ ] Bluetooth Admin
		-  [ ] Bluetooth Client
		-  [ ] Bluetooth Server
		-  [ ] Download
		-  [ ] FTP
		-  [ ] Network
		-  [ ] Web
		-  [ ] WiFi
  	-  [ ] Google
		-  [x] Overview
		-  [ ] Google Account Picker
		-  [ ] Google Maps
  	-  [ ] Monetization
		-  [x] Overview
		-  [ ] AdMob Banner
		-  [ ] AdMob Interstitial
		-  [ ] AdMob Rewarded Video
		-  [ ] Amazon Banner
		-  [ ] Amazon Interstitial
		-  [ ] Facebook Banner
		-  [ ] Facebook Interstitial
		-  [ ] In App Billing
		-  [x] Leadbolt
		-  [ ] Whitemobi
 	-  [ ] LEGO Mindstorms
		-  [x] Overview
		-  [ ] NXT Drive
		-  [ ] NXT Color Sensor
		-  [ ] NXT Light Sensor
		-  [ ] NXT Sound Sensor
		-  [ ] NXT Touch Sensor
		-  [ ] NXT Ultrasonic Sensor
		-  [ ] NXT Direct Commands
		-  [ ] EV3 Motors
		-  [ ] EV3 Color Sensor
		-  [ ] EV3 Gyro Sensor
		-  [ ] EV3 Touch Sensor
		-  [ ] EV3 Ultrasonic Sensor
		-  [ ] EV3 Sound
		-  [ ] EV3 UI
		-  [ ] EV3 Commands
  	-  [ ] Experimental
		-  [x] Overview
		-  [ ] Chrome Custom Tabs
		-  [ ] Cloud DB
		-  [ ] Notification
		-  [ ] Push Notifications
		-  [ ] Shell
		-  [x] Shortcut Badge
-  [ ] Blocks
	-  [x] Overview
	-  [x] Control
	-  [x] Logic
	-  [x] Math
	-  [x] Text
	-  [x] Lists
	-  [x] Colors
	-  [x] Variables
	-  [x] Procedures
	-  [ ] Any Component

**Comment by AryaDeepanshu** [comment]
I completed the accelerometer and Bar Code scanner. You can Verify the edition

**Comment by imijanur** [comment]
Page loaded block is not working. can you please check it out. It was working fine when I used before
