### ISSUE TITLE
Working on Documentation

### ISSUE THREAD

**Issue by barreeeiroo** [Kodular/Documentation#56]
Continuing Issue #1, I would like to note that I'm currently working on a script that automatically generates all needed documentation. All blocks and components have descriptions, meaning they can be passed into documentation without needing to manually write every single page.

Work will be done at github.com/barreeeiroo/Documentation

**Comment by fahadboss10** [comment]
Automatic work will be good so that no components' doc will be empty. And if needed for a particular component, it can be improved later.
Good work! 👍
